HTML-Forms: Mint Signup Page
DeliceLydia/HTML-Forms pull request #1
Opened 2020-08-19 15:24 UTC by DeliceLydia

In this project, we:

- Created a replica of mint.com signup page using HTML and CSS

2020-08-19 16:50 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] your PR description can be more descriptive, please change it.

- I included more required changes below, please check them out

## Optional

- [ ] make the email and password inputs required


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-19 16:50 UTC, Spayco commented on index.html
> +        </div>
- [ ] [REQUIRED] the Intuit products should be in images and text, not a screenshot, please fix that

2020-08-19 16:50 UTC, Spayco commented on index.html
> +                </button>
- [ ] the button should have a `submit` type, not `button`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))

2020-08-20 13:46 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello @DeliceLydia @eananti** 
Amazing job :tada: :tada: :tada:  you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: :muscle:
Don't forget to merge with the master branch

Keep going like this  :clap: :clap:

Oscar Andrés Russi Porras

2020-08-20 14:44 UTC, merged